### PR TITLE
Integrate hardnested support 2

### PR DESCRIPTION
**Pull request by gelotus**
Based on @vk496 work, code cleaning (most in proxmark parts), reworked build system, add win32 with msvc 2019 + clang, unique tree for msvc and gnu build tools, simd parts are compiled only on x86 platforms, removed gcc only macros, added -F option to force the hardnested attack key extraction, removed now unused parameters. Tested on windows 10 x64 and ubuntu 20.04 x64, just works with no bugs.

### CODE REVIEW

**Comment by doegox** [comment]
wow, honestly this is just a new project deserving its own repo, not a PR...
I can push it as https://github.com/nfc-tools/mfoc-hardnested if you prefer to promote it here rather than on your account.
What do you think ?

**Comment by gelotus** [comment]
The choice is your, I'll be just happy if you want to do. Let me know if you want to do because there are some references to my github page inside

**Comment by doegox** [comment]
Done https://github.com/nfc-tools/mfoc-hardnested/
@gelotus and @vk496 you got invitations to be able to push directly to it.
And yes @gelotus you might change the URLs to the nfc-tools one now.

**Comment by vk496** [comment]
@doegox can you send me the invitation link again?

I have ready some commits :)

**Comment by doegox** [comment]
@vk496 done, you can visit https://github.com/nfc-tools/mfoc-hardnested/invitations

**Pull request closed without merging**
