### PR TITLE
Fixed readme compiling options

### PR DESCRIPTION
**Pull request by ceres-c**
One last step was missing

### CODE REVIEW

**Comment by iceman1001** [comment]
yeah, that one bite me aswell..
@doegox   merge?

**Comment by smortex** [comment]
All these steps (`libtoolize`, `aclocal`. `autoheader`, `autoconf`, `automake`) can be replaced by a single:

```
autoreconf -is
```

Ways simpler… Do you mind updating the pull-request?

**Comment by iceman1001** [comment]
Unrelated but would the one-liner also work on mfcuk repo?

**Comment by smortex** [comment]
> Unrelated but would the one-liner also work on mfcuk repo?

It should :-)  I guess I commented o the PR you are speaking about: https://github.com/nfc-tools/mfcuk/pull/49#discussion_r165022870

**Comment by iceman1001** [comment]
You certainly did while I was commenting here. You are faster than I exected.  I will continue this on the correct related issue in the aforemented repo.

**Comment by ceres-c** [comment]
You're quite right @smortex, I've updated the PR

**Pull request merged**
